### ISSUE TITLE
Enhancement: SendAndReceiveAsync

### ISSUE THREAD

**Issue by brcaswell** [Phyyl/ObooltNet#1]
please review the following SO question regarding your class.
http://stackoverflow.com/questions/32206244/how-to-handle-some-asynchronous-tcpclient-responses

**Comment by brcaswell** [comment]
I meant to mark this with an enhancement label.. I'm not too familiar with github.

**Comment by Phyyl** [comment]
Hi, Glad you're using my class! I made a video demonstrating a way to handle requests and responses in TCP. I didn't use the Oboolt class, but the class is only for demonstrating, not really for production. I encourage you to watch the video here: https://www.youtube.com/watch?v=NGRAMMe9RK4 .
If you have any questions, you can reach me here, on twitter or through my email at contact@phyyl.me
